[package]
name = "swsurface"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
winit = ">= 0.20.0-alpha1, < 0.21"

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
objc = "0.2.6"

[target.'cfg(target_os = "macos")'.dependencies]
cgl = "0.2"
cocoa = "0.18"
core-foundation = "0.6"
core-graphics = "0.17"
owning_ref = "0.4.0"

[dev-dependencies]
lazy_static = "1"